name: 'Kelly Melsted '
favicon: null
layout_spectrum: 0.4130638735368848
typography_spectrum: 0.516337608685717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.48773055896162987
  lightness: 0.6737050856463611
  saturation: 0.7792315678671002
  rhythmicContrast: 0.5324154908303171
purpose: []
